version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - db-local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d postgres -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  ticket-service:
    container_name: ticket-service
    build:
      context: .
      dockerfile: Dockerfile.ticket-service
    environment:
      PORT: "8070"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8070"
    networks:
      - db-local
      - ticket

  flight-service:
    container_name: flight-service
    build:
      context: .
      dockerfile: Dockerfile.flight-service
    environment:
      PORT: "8060"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8060:8060"
    networks:
      - db-local
      - flight

  bonus-service:
    container_name: bonus-service
    build:
      context: .
      dockerfile: Dockerfile.bonus-service
    environment:
      PORT: "8050"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8050:8050"
    networks:
      - db-local
      - bonus

  gateway-service:
    build:
      context: ./
      dockerfile: Dockerfile.gateway-service
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - ticket-service
      - flight-service
      - bonus-service
    networks:
      - flight
      - bonus
      - ticket

networks:
  db-local:
  flight:
  bonus:
  ticket:

volumes:
  db-data: