name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build
      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run Unit Tests
        run: |
          cd src/bonus-service/handlers && go test && cd ../../..
          cd src/flight-service/handlers && go test && cd ../../..
          cd src/ticket-service/handlers && go test && cd ../../..

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your variant
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and publish images
        timeout-minutes: 15
        run: |
          docker push bdgn111/lab4-gateway
          docker push bdgn111/lab4-tickets
          docker push bdgn111/lab4-flights
          docker push bdgn111/lab4-bonuses
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      
      - name: Try the cluster !
        run: |
          kubectl get pods -A
 
      - name: Create Namespace
        run: |
          kubectl create namespace bdgn111
          
      - name: Deploy DB and services
        run: |
          kubectl get namespace
          
          cd k8s
          echo "------------------Deploy DB------------------"
          helm delete postgres --namespace bdgn111 --ignore-not-found
          helm install -n bdgn111 postgres ./postgres
          
          echo "------------------Deploy services------------------"
          helm delete tickets --namespace bdgn111 --ignore-not-found
          helm install -n bdgn111 tickets ./services
      
      - name: Wait 60s
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      
      - name: All resources from namespace bdgn111
        run: |
          kubectl get all -n bdgn111

      # - uses: education/autograding@v1
      #   id: autograder
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 2
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v